typography_spectrum: 0.4391632077749819
color:
  brandStrength: 0.9501328044570982
  lightness: 1
  saturation: 0.5553191
  rhythmicContrast: 0
  brandColors:
    - '#962D3E'
    - '#343642'
    - '#979C9C'
    - '#F2EBC7'
    - '#348899'
layout_spectrum: 0.2148936
logo: null
name: curls
navigation:
  - name: Facebook
    url: 'https://www.facebook.com/curlsmy/'
    type: external
collections:
  - index:
      navigable: true
      path: /
      number: 15
      paginate: true
    feed:
      format: rss
      path: /rss.xml
      number: 10
    permalink:
      path: '/:title/'
title: ''
